<#
    .SYNOPSIS
    Tags new resource group with creator's user name.

    .DESCRIPTION
    This Azure function automatically tags newly created resource group with creator's user name. 
    BDTagCreatorFunction is triggered by subscribed event created with Azure Event Grid. 
    Usage of filters in Azure Event Grid allows to separate only events concerning creation of new resource group. 
    All necessery data, such as: resource group URI and it's creator are imported from event log generated by Azure Event Grid.  

    .PARAMETER eventGridEvent
    Passed automatically by Azure Event Grid, contains all information about event occured.

    .PARAMETER TriggerMetadata
    Passed automatically by Azure Event Grid, contains meta data about event occured.

    .INPUTS
    All needed objects passed by Azure Event Grid.

    .OUTPUTS
    Logging data goes to the output stream.

    .EXAMPLE
    Function not executed manually. 

    .NOTES
    Version:    1.0
    Author:     B.Dylik
    Date:       22.07.2022

    .LINKS  
    Useful documentation:
    https://azure.microsoft.com/pl-pl/services/event-grid/#overview
    https://docs.microsoft.com/pl-pl/azure/azure-functions/functions-overview
#>


param($eventGridEvent, $TriggerMetadata)

# Show event log formatted in JSON
Write-Information "Event log in JSON:"
$eventGridEvent | ConvertTo-Json | Write-Output

# Get all needed details from the log: creator name and resource group URI
$creatorValue = $eventGridEvent.data.claims.name
$rgURI = $eventGridEvent.data.resourceUri

# Show information for diagnostics purposes
Write-Information "<$rgURI> is the resource group URI"
Write-Information "<$creatorValue> will be a value for the creator tag"

# Create key/value variable as a hash table
$tag = @{"Creator" = "$creatorValue"}

# Update created RG tag with Update-AzTag cmdlet (merge operation does not remove previously added tags)
Try {
    Update-AzTag -ResourceId $rgURI -Tag $tag -Operation Merge -ErrorAction Stop
}
Catch {
    $Message = $_.Exception.message
    Write-Information "Error occured while updating tags. Details below:"
    Write-Information $Message
    Break
}

